version: '3.7'

services:
  api:
    build:
      context: ./CoreApi
      dockerfile: Dockerfile
    networks:
      - bridge-network

  cypresstests:
    build:
      args:
        CYPRESS_KEY: "defaultvalue"
      context: ./cypress.io
      dockerfile: Dockerfile
    networks:
      - bridge-network

networks:
  bridge-network:
    driver: bridge
