trigger:
  branches:
    include:
      - master
pr:
  branches:
    include:
      - master

steps:
  - task: DockerCompose@0
    displayName: "Build Docker services"
    inputs:
      dockerComposeFile: "docker-compose.yml"
      dockerComposeCommand: "build --build-arg CYPRESS_KEY=\"${{ CYPRESS_KEY }}\""

  - task: DockerCompose@0
    displayName: "Run Docker services"
    inputs:
      dockerComposeFile: "docker-compose.yml"
      dockerComposeCommand: "up --abort-on-container-exit"